const now = new Date().toISOString();

export const seedData = {
  companies: [
    {
      id: 'company-aurora',
      name: 'Aurora Logistics',
      wallet_address: '7s8hVf9uD1Jx4kAurora123456789',
      created_at: now,
    },
    {
      id: 'company-skylink',
      name: 'SkyLink Robotics',
      wallet_address: '4c2pZq7mK9bSkyLink987654321',
      created_at: now,
    },
    {
      id: 'company-nimbus',
      name: 'Nimbus Droneworks',
      wallet_address: '9z1bQn6tR3pNimbus112233445',
      created_at: now,
    },
  ],
  profiles: [
    {
      id: 'profile-admin',
      email: 'admin@miaoda.com',
      username: 'admin',
      role: 'admin',
      company_id: null,
      created_at: now,
    },
    {
      id: 'profile-provider',
      email: 'provider@miaoda.com',
      username: 'provider',
      role: 'provider',
      company_id: 'company-aurora',
      created_at: now,
    },
    {
      id: 'profile-operator',
      email: 'operator@miaoda.com',
      username: 'operator',
      role: 'operator',
      company_id: 'company-skylink',
      created_at: now,
    },
  ],
  nodes: [
    {
      id: 'node-sf-01',
      name: 'Node-SF-01',
      lat: 37.7749,
      lng: -122.4194,
      capacity: 6,
      current_load: 2,
      owner_company_id: 'company-aurora',
      created_at: now,
    },
    {
      id: 'node-sf-02',
      name: 'Node-SF-02',
      lat: 37.7849,
      lng: -122.4094,
      capacity: 4,
      current_load: 1,
      owner_company_id: 'company-skylink',
      created_at: now,
    },
    {
      id: 'node-sf-03',
      name: 'Node-SF-03',
      lat: 37.7649,
      lng: -122.4294,
      capacity: 5,
      current_load: 3,
      owner_company_id: 'company-nimbus',
      created_at: now,
    },
  ],
  drones: [
    {
      id: 'drone-alpha',
      name: 'Drone-Alpha',
      company_id: 'company-aurora',
      lat: 37.7799,
      lng: -122.4194,
      battery: 82,
      status: 'flying',
      destination_lat: null,
      destination_lng: null,
      current_node_id: null,
      created_at: now,
      updated_at: now,
    },
    {
      id: 'drone-bravo',
      name: 'Drone-Bravo',
      company_id: 'company-skylink',
      lat: 37.7699,
      lng: -122.4294,
      battery: 56,
      status: 'charging',
      destination_lat: null,
      destination_lng: null,
      current_node_id: 'node-sf-03',
      created_at: now,
      updated_at: now,
    },
    {
      id: 'drone-charlie',
      name: 'Drone-Charlie',
      company_id: 'company-nimbus',
      lat: 37.7849,
      lng: -122.4094,
      battery: 22,
      status: 'en_route',
      destination_lat: 37.7749,
      destination_lng: -122.4194,
      current_node_id: null,
      created_at: now,
      updated_at: now,
    },
  ],
  transactions: [
    {
      id: 'tx-1001',
      drone_id: 'drone-bravo',
      node_id: 'node-sf-03',
      company_id: 'company-skylink',
      amount_sol: 0.018,
      timestamp: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
    },
    {
      id: 'tx-1002',
      drone_id: 'drone-charlie',
      node_id: 'node-sf-01',
      company_id: 'company-nimbus',
      amount_sol: 0.011,
      timestamp: new Date(Date.now() - 1000 * 60 * 40).toISOString(),
    },
  ],
};
